platform: linux

image_resource:
  type: registry-image
  source:
    repository: bitnami/kubectl

inputs:
- name: kubecf-pipelines
- name: kubeconfig

params:
  KUBECONFIG: kubeconfig/kubeconfig
  KUBECF_NS: kubecf

run:
  path: kubecf-pipelines/ci/tasks/wait-for-kubecf/task.sh
